---
- name: "reload {{ service_name }}"
  systemd:
    daemon_reload: yes
    name: "{{ service_name }}"
    state: reloaded

- name: "restart {{ service_name }}"
  systemd:
    daemon_reload: yes
    name: "{{ service_name }}"
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes
    name: "{{ service_name }}"
